### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by jairinhohw**
Fixed some bugs found by using large blobs

### CODE REVIEW

**Comment by jairinhohw** [comment]
I have no idea why the `macos` with `dynamic_loading` is failing

**Comment by juarezr** [comment]
> I have no idea why the `macos` with `dynamic_loading` is failing

Let me see what happened.

**Comment by jairinhohw** [comment]
Sadly no change, and the test only writes alphanumeric chars, so it shouldn't be a utf8 problem, it seems to occur on a specific lengths actually (The blob segments are received in chunks of 256 bytes in the wire, and the `\u{3}` chars seems to be 256 bytes appart of each other).
Maybe it's a bug on the shared library, as the pure_rust test passes (the `linking` is not being tested at the moment, as we could not get it to link).

**Comment by jairinhohw** [comment]
It was a problem with the `CString` use, as the segments are not `0` terminated

**Pull request merged**
