### PR TITLE
Named params support started

### PR DESCRIPTION
**Pull request by fernandobatels**
Initial work on named params support, based on struct fields.

I will implement the [struct approach](https://github.com/fernandobatels/rsfbclient/issues/48#issuecomment-690235176) directly in the main crate, because do this in an [advanced API](https://github.com/fernandobatels/rsfbclient/issues/48#issuecomment-690267889) will demand more work. We can change this after.

For now, is just some tests and WIP code

### CODE REVIEW

**Comment by fernandobatels** [comment]
I think its done. Now we can pass a struct into query parameters using the `IntoParams` derive.

**Comment by fernandobatels** [comment]
I don't why some CI tests are failing

**Comment by fernandobatels** [comment]
@cytrinox, you can check this PR? I implement the [struct approach](https://github.com/fernandobatels/rsfbclient/issues/48#issuecomment-690235176)

**Review by jairinhohw — CHANGES_REQUESTED** [review]
CI is not working because of the line 858 in file `rsfbclient-rust/src/client.rs`.

Change it to compile.
```rust
let params = match rsfbclient_core::IntoParams::to_params((1,)) {
    rsfbclient_core::ParamsType::Unamed(params) => params,
    _ => unreachable!(),
};
```

**Comment by cytrinox** [comment]
@fernandobatels Nice work, thank you. I check out the PR and do some tests with a productive database copy.

Is NULL-binding possible? For example, instead of:

````rust
 #[derive(Clone, IntoParams)]
        struct User {
            pub name: String,
            pub age: i32
        };
````
using `Option<>`:

````rust
 #[derive(Clone, IntoParams)]
        struct User {
            pub name: String,
            pub age: Option<i32>
        };
````

**Comment by cytrinox** [comment]
I'm unable to build a working test binary:

````
   Compiling fbparams1 v0.1.0 (C:\Users\vogelbacher\src\fbparams1)
error[E0432]: unresolved import `rsfbclient_core`
  --> src\main.rs:4:17
   |
4  | #[derive(Clone, IntoParams)]
   |                 ^^^^^^^^^^
   |                 |
   |                 use of undeclared crate or module `rsfbclient_core`
   |                 in this macro invocation
   |
  ::: C:\Users\vogelbacher\src\rsfbclient\rsfbclient-derive\src\lib.rs:10:1
   |
10 | pub fn into_params_derive(input: TokenStream) -> TokenStream {
   | ------------------------------------------------------------ in this expansion of `#[derive(IntoParams)]`

````

My cargo.toml is:

````
[package]
name = "fbparams1"
version = "0.1.0"
authors = ["Daniel Vogelbacher <XXX>"]
edition = "2018"

[dependencies.rsfbclient]
default-features = false
features=["pure_rust", "date_time", "pool"]
path = "../rsfbclient"
````

Any idea what is causing the problem?

**Comment by cytrinox** [comment]
After patching the code I was able to build a sample program. Even `Option<>` parameters works fine.

````
diff --git a/rsfbclient-derive/src/lib.rs b/rsfbclient-derive/src/lib.rs
index 45e9bd7..d75ae88 100644
--- a/rsfbclient-derive/src/lib.rs
+++ b/rsfbclient-derive/src/lib.rs
@@ -27,7 +27,7 @@ pub fn into_params_derive(input: TokenStream) -> TokenStream {
         });

     let st_impl = quote! {
-        use rsfbclient_core::{IntoParams, IntoParam, ParamsType};
+        use rsfbclient::{IntoParams, IntoParam, ParamsType};
         use std::collections::HashMap;

         impl IntoParams for #st_name {
diff --git a/src/lib.rs b/src/lib.rs
index ca436d1..0dd0cfe 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -22,7 +22,7 @@ pub use crate::{
     statement::Statement,
     transaction::Transaction,
 };
-pub use rsfbclient_core::{charset, Column, Dialect, FbError, FromRow, IntoParam, Row, SqlType};
+pub use rsfbclient_core::{charset, Column, Dialect, FbError, FromRow, IntoParam, IntoParams, ParamsType, Row, SqlType};
````

**Comment by fernandobatels** [comment]
> CI is not working because of the line 858 in file `rsfbclient-rust/src/client.rs`.
> 
> Change it to compile.
> 
> ```rust
> let params = match rsfbclient_core::IntoParams::to_params((1,)) {
>     rsfbclient_core::ParamsType::Unamed(params) => params,
>     _ => unreachable!(),
> };
> ```

My fault. Thanks.

**Comment by fernandobatels** [comment]
> After patching the code I was able to build a sample program. Even `Option<>` parameters works fine.
> 
> ```
> diff --git a/rsfbclient-derive/src/lib.rs b/rsfbclient-derive/src/lib.rs
> index 45e9bd7..d75ae88 100644
> --- a/rsfbclient-derive/src/lib.rs
> +++ b/rsfbclient-derive/src/lib.rs
> @@ -27,7 +27,7 @@ pub fn into_params_derive(input: TokenStream) -> TokenStream {
>          });
> 
>      let st_impl = quote! {
> -        use rsfbclient_core::{IntoParams, IntoParam, ParamsType};
> +        use rsfbclient::{IntoParams, IntoParam, ParamsType};
>          use std::collections::HashMap;
> 
>          impl IntoParams for #st_name {
> diff --git a/src/lib.rs b/src/lib.rs
> index ca436d1..0dd0cfe 100644
> --- a/src/lib.rs
> +++ b/src/lib.rs
> @@ -22,7 +22,7 @@ pub use crate::{
>      statement::Statement,
>      transaction::Transaction,
>  };
> -pub use rsfbclient_core::{charset, Column, Dialect, FbError, FromRow, IntoParam, Row, SqlType};
> +pub use rsfbclient_core::{charset, Column, Dialect, FbError, FromRow, IntoParam, IntoParams, ParamsType, Row, SqlType};
> ```

Nice. I will check this tonight and apply the patch. Thanks

**Comment by fernandobatels** [comment]
I have a doubt, we have support reference struct params?

**Review by jairinhohw — APPROVED** [review]

**Comment by fernandobatels** [comment]
> After patching the code I was able to build a sample program. Even `Option<>` parameters works fine.
> 
> ```
> diff --git a/rsfbclient-derive/src/lib.rs b/rsfbclient-derive/src/lib.rs
> index 45e9bd7..d75ae88 100644
> --- a/rsfbclient-derive/src/lib.rs
> +++ b/rsfbclient-derive/src/lib.rs
> @@ -27,7 +27,7 @@ pub fn into_params_derive(input: TokenStream) -> TokenStream {
>          });
> 
>      let st_impl = quote! {
> -        use rsfbclient_core::{IntoParams, IntoParam, ParamsType};
> +        use rsfbclient::{IntoParams, IntoParam, ParamsType};
>          use std::collections::HashMap;
> 
>          impl IntoParams for #st_name {
> diff --git a/src/lib.rs b/src/lib.rs
> index ca436d1..0dd0cfe 100644
> --- a/src/lib.rs
> +++ b/src/lib.rs
> @@ -22,7 +22,7 @@ pub use crate::{
>      statement::Statement,
>      transaction::Transaction,
>  };
> -pub use rsfbclient_core::{charset, Column, Dialect, FbError, FromRow, IntoParam, Row, SqlType};
> +pub use rsfbclient_core::{charset, Column, Dialect, FbError, FromRow, IntoParam, IntoParams, ParamsType, Row, SqlType};
> ```

Fixed now

**Comment by fernandobatels** [comment]
@cytrinox , with this PR, your #48 issue will be solved? Or you still need some `named_params!` macro?

**Review by afsmi — CHANGES_REQUESTED** [review]
your changes break other types of queries that use `:var` syntax.

please make the new functionality optional.

here is an example

```
let exec_block_select : &str = "
EXECUTE BLOCK
   RETURNS (outval bigint)
 as 
   declare loopvar int = 0;
   begin
     while (loopvar < 100) do begin
       for select
         :loopvar
       from
         rdb$database
       into
         :outval
       do begin
         loopvar = loopvar + 1;
         suspend;
       end
     end
   end;";


let mut conn = cbuilder().connect()?;

let rows = conn.query_iter::<(), (i64,)>(exec_block_select,())?;

for row in rows {
    let (i,) = row?;
    println!("{}", i);
}
```

**Comment by fernandobatels** [comment]
> your changes break other types of queries that use `:var` syntax.
> 
> please make the new functionality optional.
> 
> here is an example
> 
> ```
> let exec_block_select : &str = "
> EXECUTE BLOCK
>    RETURNS (outval bigint)
>  as 
>    declare loopvar int = 0;
>    begin
>      while (loopvar < 100) do begin
>        for select
>          :loopvar
>        from
>          rdb$database
>        into
>          :outval
>        do begin
>          loopvar = loopvar + 1;
>          suspend;
>        end
>      end
>    end;";
> 
> 
> let mut conn = cbuilder().connect()?;
> 
> let rows = conn.query_iter::<(), (i64,)>(exec_block_select,())?;
> 
> for row in rows {
>     let (i,) = row?;
>     println!("{}", i);
> }
> ```

I couldn't find a good way to make this optional. So, to avoid problems, now we will use a '::' for mark the named params

**Comment by cytrinox** [comment]
Please avoid introducing another syntax for named parameters at all. There are enough confusion already in the database/SQL "market". It's clearly better IMHO to not support named parameters if it can not be implemented with the default ":p" syntax.

**Comment by afsmi** [comment]
@fernandobatels 
1. I think @cytrinox is a being a bit pessimistic in their opinion about what's better or worse, but also raises a valid question about the ecosystem. it's hard to say right now how popular this crate will become (personally i think it could be really big because of c ffi)

2. Also I think it is important that we find a way to make it so that parsing/named param processing is completely **opt-in** on a per-statement basis, at least for now, because it is hard to account for all situations that may break.
    The documentation for this option should give a strong warning that it is meant for simple queries only and to thoroughly test the queries used.

To make my point, here is another example.
This time it compiles but does not give correct output.
(notice the `'` in the sql comment)
```
let select_broken_string_constant : &str = "
  /* A stick, a stone, it's the end of */
  select 'the ::road' from rdb$database;";

let mut conn = cbuilder().connect()?;
let rows = conn.query_iter::<(), (String,)>(select_broken_string_constant,())?;

for row in rows {
    let (s,) = row?;
    println!("{}", s);
}
```

**Review by jairinhohw — APPROVED** [review]

**Comment by fernandobatels** [comment]
@jairinhohw solve the '::' mark situation. This was what i had been trying to do before, but without success. The ':' mark works again, and to disable it just don't use a struct as a parameter.

**Review by afsmi — APPROVED** [review]
:+1: looks good.

can you write some documentation for the main crate/high level api, mentioning:
* derive macro
* Some/None usage in struct
* tuple vs derive struct usage in api
* caution about supported queries, with examples of some queries that will not work currently
* anything else you think is relevant?

(could be a separate pr after this one)

I can help with editing it if you want, so you just have to get the ideas expressed

**Comment by fernandobatels** [comment]
> +1 looks good.
> 
> can you write some documentation for the main crate/high level api, mentioning:
> 
>     * derive macro
> 
>     * Some/None usage in struct
> 
>     * tuple vs derive struct usage as it pertains to named params parsing
> 
>     * caution about supported queries, with examples of some queries that will not work currently
> 
>     * anything else you think is relevant?
> 
> 
> (could be a separate pr after this one)
> 
> I can help with editing it if you want, so you just have to get the ideas expressed

Done. You have more suggestions about the text?

**Comment by afsmi** [comment]
See my PR.

Additional suggestion for now or later, unrelated to that PR: replace `impl IntoParams for X` by `impl From<X> for ParamsType`, everywhere and same for `IntoParam`/`SqlType`.  No need for there to be a replica of standard traits.

**Review by afsmi — APPROVED** [review]

**Pull request merged**
